### ISSUE TITLE
Pass RCMD check + create first release

### ISSUE THREAD

**Issue by andreavargasmon** [ixpantia/googleErrorReportingR#30]

**Comment by andreavargasmon** [comment]
```
> test_check("googleErrorReportingR")
Error in `test_dir()`:
! No test files found
Backtrace:
    ▆
 1. └─testthat::test_check("googleErrorReportingR")
 2.   └─testthat::test_dir("testthat", package = package, reporter = reporter, ..., load_package = "installed")
 3.     └─rlang::abort("No test files found")
Execution halted

1 error ✖ | 3 warnings ✖ | 0 notes ✔
Error: R CMD check found ERRORs
Execution halted

Exited with status 1.

```

**Comment by andreavargasmon** [comment]
current situation after some minor details:
```
❯ checking Rd files ... WARNING
  NULL

0 errors ✔ | 1 warning ✖ | 0 notes ✔
Error: R CMD check found WARNINGs
Execution halted

Exited with status 1.

```

**Comment by andreavargasmon** [comment]
but this is a confirmed bug on the rcmdcheck side:

https://bugs.r-project.org/show_bug.cgi?id=18388
https://github.com/r-lib/rcmdcheck/issues/184

even Jenny Bryan is seeing it:
<img width="945" alt="Screen Shot 2022-08-24 at 19 11 57" src="https://user-images.githubusercontent.com/53089319/186551556-2e94a7c9-8113-4f59-b0b8-670c5182e111.png">

**Comment by andreavargasmon** [comment]
I think this can be safely ignored for now

**Comment by FvD** [comment]
I saw a few additional warnings and resolved them

1. not al parameters were documented in report_error
2. MIT licence requires + file LICENCE
